/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package login_do_sistema;

import Conexao_Com_Banco_De_Dados.Conexao_Com_Banco_De_Dados_Derby_Alone;
import br.com.jmary.home.Home;
import br.com.jmary.home.jpa.DB_Bean;
import br.com.jmary.home.jpa.JPAUtil;
import br.com.jmary.utilidades.Exportando;
import br.com.jmary.utilidades.JOPM;
import java.io.FileInputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Arrays;
import java.util.List;
import java.util.Properties;
import javax.persistence.Query;
import javax.swing.ImageIcon;
import usuarios_do_sistema_beans.UsuarioSistema;

/**
 *
 * @author admin
 */
public class Login_Do_Sistema extends javax.swing.JPanel {

    Home Home;
    /**
     * Creates new form Exercicios_00_Portugues_Indice
     * @param Home2
     */
    public Login_Do_Sistema( Home Home2) {
        Home = Home2;        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        Properties_Criado1 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel24 = new javax.swing.JPanel();
        JPOpcao_17 = new javax.swing.JPanel();
        jLabel68 = new javax.swing.JLabel();
        JPOpcao_18 = new javax.swing.JPanel();
        taNomeUsuario = new javax.swing.JTextField();
        jPanel26 = new javax.swing.JPanel();
        JPOpcao_19 = new javax.swing.JPanel();
        jLabel69 = new javax.swing.JLabel();
        JPOpcao_20 = new javax.swing.JPanel();
        taSenha = new javax.swing.JPasswordField();
        jButton4 = new javax.swing.JButton();
        JPOpcao_22 = new javax.swing.JPanel();
        taStatus = new javax.swing.JTextField();

        setPreferredSize(new java.awt.Dimension(602, 378));
        setLayout(new java.awt.GridBagLayout());

        Properties_Criado1.setBorder(new javax.swing.border.MatteBorder(null));
        Properties_Criado1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Properties_Criado1.setPreferredSize(new java.awt.Dimension(585, 458));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 40)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("LOGIN     ");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home_controle_menus_norte/imagens/login.png"))); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home_controle_menus_norte/imagens/ip_conexao.png"))); // NOI18N
        jLabel5.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel5MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addGap(18, 18, 18))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel4))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/jmary/home/imagens/logocangaco.png"))); // NOI18N

        JPOpcao_17.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 1, new java.awt.Color(153, 0, 153)));
        JPOpcao_17.setPreferredSize(new java.awt.Dimension(284, 27));
        JPOpcao_17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JPOpcao_17MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JPOpcao_17MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                JPOpcao_17MousePressed(evt);
            }
        });

        jLabel68.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel68.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel68.setText("Usuário.: ");

        javax.swing.GroupLayout JPOpcao_17Layout = new javax.swing.GroupLayout(JPOpcao_17);
        JPOpcao_17.setLayout(JPOpcao_17Layout);
        JPOpcao_17Layout.setHorizontalGroup(
            JPOpcao_17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel68, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        JPOpcao_17Layout.setVerticalGroup(
            JPOpcao_17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel68, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
        );

        JPOpcao_18.setBackground(new java.awt.Color(255, 255, 255));
        JPOpcao_18.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 0, 153)));
        JPOpcao_18.setPreferredSize(new java.awt.Dimension(284, 27));
        JPOpcao_18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JPOpcao_18MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JPOpcao_18MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                JPOpcao_18MousePressed(evt);
            }
        });

        taNomeUsuario.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        taNomeUsuario.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(201, 239, 237), 1, true));
        taNomeUsuario.setPreferredSize(new java.awt.Dimension(209, 25));
        taNomeUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                taNomeUsuarioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                taNomeUsuarioMouseExited(evt);
            }
        });
        taNomeUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                taNomeUsuarioKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout JPOpcao_18Layout = new javax.swing.GroupLayout(JPOpcao_18);
        JPOpcao_18.setLayout(JPOpcao_18Layout);
        JPOpcao_18Layout.setHorizontalGroup(
            JPOpcao_18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(taNomeUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
        );
        JPOpcao_18Layout.setVerticalGroup(
            JPOpcao_18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPOpcao_18Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(taNomeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel24Layout = new javax.swing.GroupLayout(jPanel24);
        jPanel24.setLayout(jPanel24Layout);
        jPanel24Layout.setHorizontalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel24Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JPOpcao_17, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JPOpcao_18, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel24Layout.setVerticalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPOpcao_18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(JPOpcao_17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        JPOpcao_19.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 1, new java.awt.Color(153, 0, 153)));
        JPOpcao_19.setPreferredSize(new java.awt.Dimension(284, 27));
        JPOpcao_19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JPOpcao_19MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JPOpcao_19MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                JPOpcao_19MousePressed(evt);
            }
        });

        jLabel69.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel69.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel69.setText("Senha.: ");

        javax.swing.GroupLayout JPOpcao_19Layout = new javax.swing.GroupLayout(JPOpcao_19);
        JPOpcao_19.setLayout(JPOpcao_19Layout);
        JPOpcao_19Layout.setHorizontalGroup(
            JPOpcao_19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel69, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        JPOpcao_19Layout.setVerticalGroup(
            JPOpcao_19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel69, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
        );

        JPOpcao_20.setBackground(new java.awt.Color(255, 255, 255));
        JPOpcao_20.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 0, 153)));
        JPOpcao_20.setPreferredSize(new java.awt.Dimension(284, 27));
        JPOpcao_20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JPOpcao_20MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JPOpcao_20MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                JPOpcao_20MousePressed(evt);
            }
        });

        taSenha.setBorder(null);

        javax.swing.GroupLayout JPOpcao_20Layout = new javax.swing.GroupLayout(JPOpcao_20);
        JPOpcao_20.setLayout(JPOpcao_20Layout);
        JPOpcao_20Layout.setHorizontalGroup(
            JPOpcao_20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(taSenha, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
        );
        JPOpcao_20Layout.setVerticalGroup(
            JPOpcao_20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(taSenha)
        );

        javax.swing.GroupLayout jPanel26Layout = new javax.swing.GroupLayout(jPanel26);
        jPanel26.setLayout(jPanel26Layout);
        jPanel26Layout.setHorizontalGroup(
            jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel26Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JPOpcao_19, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JPOpcao_20, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel26Layout.setVerticalGroup(
            jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPOpcao_20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(JPOpcao_19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jPanel24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jButton4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/conexao_com_banco_de_dados_imagens/conectar.gif"))); // NOI18N
        jButton4.setText("Conectar");
        jButton4.setPreferredSize(new java.awt.Dimension(91, 27));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        JPOpcao_22.setBackground(new java.awt.Color(255, 255, 255));
        JPOpcao_22.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 0, 153)));
        JPOpcao_22.setPreferredSize(new java.awt.Dimension(284, 27));
        JPOpcao_22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JPOpcao_22MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JPOpcao_22MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                JPOpcao_22MousePressed(evt);
            }
        });

        taStatus.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        taStatus.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(201, 239, 237), 1, true));
        taStatus.setPreferredSize(new java.awt.Dimension(209, 25));
        taStatus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                taStatusMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                taStatusMouseExited(evt);
            }
        });
        taStatus.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                taStatusKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout JPOpcao_22Layout = new javax.swing.GroupLayout(JPOpcao_22);
        JPOpcao_22.setLayout(JPOpcao_22Layout);
        JPOpcao_22Layout.setHorizontalGroup(
            JPOpcao_22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(taStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        JPOpcao_22Layout.setVerticalGroup(
            JPOpcao_22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(taStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout Properties_Criado1Layout = new javax.swing.GroupLayout(Properties_Criado1);
        Properties_Criado1.setLayout(Properties_Criado1Layout);
        Properties_Criado1Layout.setHorizontalGroup(
            Properties_Criado1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Properties_Criado1Layout.createSequentialGroup()
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(JPOpcao_22, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 603, Short.MAX_VALUE)
        );
        Properties_Criado1Layout.setVerticalGroup(
            Properties_Criado1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Properties_Criado1Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(JPOpcao_22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 12;
        gridBagConstraints.ipady = -84;
        gridBagConstraints.insets = new java.awt.Insets(6, 4, 8, 5);
        add(Properties_Criado1, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        
        if( !taNomeUsuario.getText().trim().equals("") ){
            
            login();
        }
        else{
                
            taNomeUsuario.requestFocus();
                    
            Class<imagens_internas.Imagens_Internas> clazzHome = imagens_internas.Imagens_Internas.class;
            JOPM JOptionPaneMod = new JOPM( 1, "CAMPO USUÁRIO\n"
                    + "\n"
                    + "\nO CAMPO USUÁRIO ESTÁ VAZIO!\n"
                    + "\n"
                    + "\nPARA CADASTRAR É NECESSÁRIO INFORMAR UM NOME DE USUÁRIO!\n"
                    + "\n"
                    + "\nOK PARA PROSSEGUIR"
                    ,"Class: " + this.getClass().getName(), 
                    new ImageIcon( clazzHome.getResource("logocangaco2.png")) );
        }
    }//GEN-LAST:event_jButton4ActionPerformed
        
    private void JPOpcao_17MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPOpcao_17MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_JPOpcao_17MouseEntered

    private void JPOpcao_17MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPOpcao_17MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_JPOpcao_17MouseExited

    private void JPOpcao_17MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPOpcao_17MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_JPOpcao_17MousePressed

    private void JPOpcao_18MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPOpcao_18MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_JPOpcao_18MouseEntered

    private void JPOpcao_18MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPOpcao_18MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_JPOpcao_18MouseExited

    private void JPOpcao_18MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPOpcao_18MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_JPOpcao_18MousePressed

    private void JPOpcao_19MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPOpcao_19MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_JPOpcao_19MouseEntered

    private void JPOpcao_19MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPOpcao_19MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_JPOpcao_19MouseExited

    private void JPOpcao_19MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPOpcao_19MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_JPOpcao_19MousePressed

    private void JPOpcao_20MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPOpcao_20MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_JPOpcao_20MouseEntered

    private void JPOpcao_20MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPOpcao_20MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_JPOpcao_20MouseExited

    private void JPOpcao_20MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPOpcao_20MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_JPOpcao_20MousePressed

    private void taNomeUsuarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_taNomeUsuarioMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_taNomeUsuarioMouseEntered

    private void taNomeUsuarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_taNomeUsuarioMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_taNomeUsuarioMouseExited

    private void taNomeUsuarioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_taNomeUsuarioKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_taNomeUsuarioKeyReleased

    private void taStatusMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_taStatusMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_taStatusMouseEntered

    private void taStatusMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_taStatusMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_taStatusMouseExited

    private void taStatusKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_taStatusKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_taStatusKeyReleased

    private void JPOpcao_22MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPOpcao_22MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_JPOpcao_22MouseEntered

    private void JPOpcao_22MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPOpcao_22MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_JPOpcao_22MouseExited

    private void JPOpcao_22MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPOpcao_22MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_JPOpcao_22MousePressed

    Exportando Exportando;
    private void jLabel5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MousePressed
        new Thread() {   @Override public void run() { try { Thread.sleep( 1 );
            Exportando = new Exportando("ABRINDO...");
            Exportando.setVisible(true);Exportando.pbg.setMinimum(0);
            Exportando.pbg.setMaximum( 100 );
            Exportando.pbg.setValue( 50 );
            
            //Home.ControleTabs.removerTabSelecionado();
            Home.ControleTabs.AddTabsAoHome("Conexao Com Banco De Dados", "livroTp.gif", 
                    new Conexao_Com_Banco_De_Dados_Derby_Alone(Home) );

            Exportando.fechar();
        } catch( Exception e ){ Exportando.fechar(); e.printStackTrace(); } } }.start();
    }//GEN-LAST:event_jLabel5MousePressed
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPOpcao_17;
    private javax.swing.JPanel JPOpcao_18;
    private javax.swing.JPanel JPOpcao_19;
    private javax.swing.JPanel JPOpcao_20;
    private javax.swing.JPanel JPOpcao_22;
    private javax.swing.JPanel Properties_Criado1;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel3;
    public javax.swing.JTextField taNomeUsuario;
    private javax.swing.JPasswordField taSenha;
    public javax.swing.JTextField taStatus;
    // End of variables declaration//GEN-END:variables
    
//USUÁRIO ADMIN DO BANCO DE DADOS//////////////////////////////////////////////////////////////////////////////                
String usuario_con_generico = "cleilson";                
String senha_con_generica = "23071354";   
//USUÁRIO ADMIN DO BANCO DE DADOS//////////////////////////////////////////////////////////////////////////////      
    private void login(){    

        new Thread() {   @Override public void run() { try { Thread.sleep( 1 );
        
///MESMO DA CONEXÃO COM BANCO///////////////////////////////////////////////////////////////////////////////////////////// 
            String nomeArquivoPropertiesASerCriado = "db_conf_derby";
            //String arquivoASerCriado = System.getProperty("user.dir") + "\\" + nomeArquivoPropertiesASerCriado + ".properties";
            
            Properties props = new Properties();
            try{
                
                FileInputStream in = new FileInputStream( nomeArquivoPropertiesASerCriado + ".properties" );
                props.loadFromXML(in);
                in.close();
            }catch( Exception e ){}

            //props.put("usuario", usuario);
            //props.put("senha",   senhaX);
            String usuario = "";   try{ usuario  = taNomeUsuario.getText().trim().toUpperCase();  } catch( Exception e ){}
            char[] senhaX  = null; try{ senhaX   = taSenha.getPassword();           } catch( Exception e ){}
            String senha   = "";   try{ senha    = Arrays.toString(senhaX);         } catch( Exception e ){}
            String senhaY  = "";   try{ senhaY   = senha.replace("[", "");          } catch( Exception e ){}
            String senhaY2 = "";   try{ senhaY2  = senhaY.replace("]", "");         } catch( Exception e ){}
            String senhaY3 = "";   try{ senhaY3  = senhaY2.replace(" ", "");        } catch( Exception e ){}
            String senhaY4 = "";   try{ senhaY4  = senhaY3.replace(",", "");        } catch( Exception e ){}
///MESMO DA CONEXÃO COM BANCO/////////////////////////////////////////////////////////////////////////////////////////////             
            
            UsuarioSistema UsuarioSistema = null;
            try{
///MESMO DO HOME/////////////////////////////////////////////////////////////////////////////////////////////                 
                String tipo_de_conexao = props.getProperty("tipo_de_conexao"); 
                String ip_do_servidor  = props.getProperty("ip_do_servidor");
                String porta_servidor  = props.getProperty("porta_servidor");
                String tipoDeBanco     = props.getProperty("tipoDeBanco");
                String nomeDoBanco     = props.getProperty("nomeDoBanco");
                //String usuario         = props.getProperty("usuario");
                //String senha           = props.getProperty("senha");  
                String endereco_db     = props.getProperty("endereco_db");     
                String driver          = props.getProperty("driver"); 
                ////////////////////////////////////////////////////////////////////////////////////////////////               
                String driverAlone     = ""; //"org.apache.derby.jdbc.EmbeddedDriver"; 
                String driverNetwork   = ""; //"org.apache.derby.jdbc.ClientDriver"; 

                String urlAlone        = "jdbc:"+tipoDeBanco+":" + endereco_db + "/" + nomeDoBanco+";" + "user="+usuario_con_generico+";" + "password="+senha_con_generica+"";
                String urlNetwork      = "jdbc:"+tipoDeBanco+"://" + ip_do_servidor + ":"+porta_servidor+"/" + nomeDoBanco+";" + "user="+usuario_con_generico+";" + "password="+senha_con_generica+"";
///MESMO DO HOME/////////////////////////////////////////////////////////////////////////////////////////////                 
                Connection con = null;                
                if( tipo_de_conexao.equals("alone") ){   
                    
///MESMO DO CRIAR BANCO/////////////////////////////////////////////////////////////////////////////////////////////                 
                    driverAlone = driver;
                    System.out.println("OK - Usuarios_do_Sistema - "+DB_Bean.urlAlone);                    
                    try{
                    
                        Class.forName( driver ); 
                        con = DriverManager.getConnection( urlAlone );
                        
                        System.out.println("OK - CONEXÃO - "+tipo_de_conexao);
                    }catch( Exception e ){
                        System.out.println("NÃO OK - CONEXÃO - "+tipo_de_conexao);
                    }
                }
                else if( tipo_de_conexao.equals("network") ){      
                
                    driverNetwork = driver;
                    System.out.println("OK - Usuarios_do_Sistema - "+DB_Bean.urlNetwork);
                    try{
                    
                        Class.forName( driver ); 
                        con = DriverManager.getConnection( urlNetwork );
                        
                        System.out.println("OK - CONEXÃO - "+tipo_de_conexao);
                    }catch( Exception e ){
                        System.out.println("NÃO OK - CONEXÃO - "+tipo_de_conexao);
                    }
///MESMO DO CRIAR BANCO/////////////////////////////////////////////////////////////////////////////////////////////  

                }
                
//////////////////////////////////////////////////////////////////////////////////////////////// 
                try{
                    PreparedStatement pstm;
                    ResultSet rs = null;
                    try{
                        pstm = con.prepareStatement("SELECT * FROM JM.USUARIO_SISTEMA WHERE LOGIN = ? AND SENHA = ?");
                        pstm.setString(1, usuario);
                        pstm.setString(2, senhaY4);
                        rs = pstm.executeQuery();
                    }catch( Exception e ){
                        System.out.println("ERRO NO - PreparedStatement");
                        e.printStackTrace();
                    }
                
                    UsuarioSistema = new UsuarioSistema();
                    try{ UsuarioSistema.setLogin(""); }catch( Exception e ){}
                    while(rs.next()) {
                    
                        UsuarioSistema.setId(rs.getInt("ID") );
                        UsuarioSistema.setLogin(rs.getString("LOGIN") );
                        UsuarioSistema.setSenha(rs.getString("SENHA") );
                        UsuarioSistema.setPermitirAcessoAoSistema(rs.getString("PERMITIR_ACESSO_AO_SISTEMA") );
                    }
                }catch( Exception e ){
                    //System.out.println("ERRO NO - PreparedStatement");
                    //e.printStackTrace();
                }
////////////////////////////////////////////////////////////////////////////////////////////////   

            }catch( Exception e ){ }
                
            String rbusca = ""; 
            try{ rbusca = UsuarioSistema.getLogin(); }catch( Exception e ){}
            
            try{ 
/*////LOGIN///*/if( !rbusca.equals("") ){
    
                    System.out.println("UsuarioSistema - Consultado - ID - "+UsuarioSistema.getId());
                    System.out.println("UsuarioSistema - Consultado - LOGIN - "+UsuarioSistema.getLogin());
                    System.out.println("UsuarioSistema - Consultado - SENHA - "+UsuarioSistema.getSenha());

/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////                    
                    verificar_Se_Usuario_Tem_Permissao( UsuarioSistema, props ); 
/////////////////////////////////////////////////////////////////////////                    
                }
                else{
                
                    Class<imagens_internas.Imagens_Internas> clazzHome = imagens_internas.Imagens_Internas.class;
                    JOPM JOptionPaneMod = new JOPM( 1, "LOGIN\n"
                            + "\n"
                            + "\nSTATUS DA TENTATIVA DE LOGIN"
                            + "\n"
                            + "\nUSUÁRIO E/OU SENHA NÃO CONFERE\n"
                            + "\n"
                            + "\nOK PARA PROSSEGUIR"
                            ,"Class: " + this.getClass().getName(), 
                            new ImageIcon( clazzHome.getResource("logocangaco2.png")) );
                }
            }catch( Exception e ){
                System.out.println("ERRO NO2 - String rbusca = \"\";");
                e.printStackTrace();
                
                Class<imagens_internas.Imagens_Internas> clazzHome = imagens_internas.Imagens_Internas.class;
                    JOPM JOptionPaneMod = new JOPM( 1, "LOGIN\n"
                            + "\n"
                            + "\nSTATUS DA TENTATIVA (Exception e)"
                            + "\n"
                            + "\nUSUÁRIO E/OU SENHA NÃO CONFERE\n"
                            + "\n"
                            + "\nOK PARA PROSSEGUIR"
                            ,"Class: " + this.getClass().getName(), 
                            new ImageIcon( clazzHome.getResource("logocangaco2.png")) );
            }

        } catch( Exception e ){ e.printStackTrace(); } } }.start();
    }
    
    private void verificar_Se_Usuario_Tem_Permissao( UsuarioSistema UsuarioSistema, Properties props ){        
        try {                   
        
            if( UsuarioSistema.getPermitirAcessoAoSistema().equalsIgnoreCase("SIM") ){
                
                //É UTILIZADO A SENHA ROOT PARA CRIAR A CONEXÃO, A DIFERENÇA ESTÁ NO USO DO USUÁRIO LOGADO
                //PARA GERENCIAR AS AUTORIZAÇÕES DE USO DAS TRANSAÇÕES
                Home.setar_Banco_de_Dados( props, usuario_con_generico, senha_con_generica);
                teste_de_conexao_listarTabelasDoBanco( UsuarioSistema.getId() );
            }
            else{
                
                Class<imagens_internas.Imagens_Internas> clazzHome = imagens_internas.Imagens_Internas.class;
                    JOPM JOptionPaneMod = new JOPM( 1, "LOGIN\n"
                            + "\n"
                            + "\nSTATUS DA TENTATIVA DE LOGIN"
                            + "\n"
                            + "\nUSUÁRIO NÃO TEM PERMISSÃO DE ACESSO\n"
                            + "\n"
                            + "\nOK PARA PROSSEGUIR"
                            ,"Class: " + this.getClass().getName(), 
                            new ImageIcon( clazzHome.getResource("logocangaco2.png")) );
            }
        } catch( Exception e ){
            
            Class<imagens_internas.Imagens_Internas> clazzHome = imagens_internas.Imagens_Internas.class;
                    JOPM JOptionPaneMod = new JOPM( 1, "ERRO LOGIN\n"
                            + "\n"
                            + "\nverificar_Se_Usuario_Tem_Permissao( UsuarioSistema UsuarioSistema, Properties props )"
                            + "\n"
                            + "\nSTATUS DA TENTATIVA DE LOGIN"
                            + "\n"
                            + "\nUSUÁRIO NÃO TEM PERMISSÃO DE ACESSO\n"
                            + "\n"
                            + "\nOK PARA PROSSEGUIR"
                            ,"Class: " + this.getClass().getName(), 
                            new ImageIcon( clazzHome.getResource("logocangaco2.png")) );
        }               
    }    
    
    private void teste_de_conexao_listarTabelasDoBanco( int id ){        
        /*new Thread() {   @Override public void run() {*/ try {                   
        
            Query q = JPAUtil.em().createNativeQuery("SELECT * FROM JM.USUARIO_SISTEMA WHERE ID = ?", UsuarioSistema.class );
            q.setParameter( 1, id ); 
            List<UsuarioSistema> listTo = q.getResultList();  
            for (int it = 0; it < listTo.size(); it++){
                
                Login.Usuario_Logado = listTo.get(it);
                //jComboBox1.addItem( listTo.get(it).getTeste1() );
                break;
            }                                    
            
            taStatus.setText("Conexão Estabelecida Com Sucesso - " + Login.Usuario_Logado.getLogin() );
            //taStatus.setText("Conexão Não Estabelecids" );
        } catch( Exception e ){ 
            
            //taStatus.setText("Conexão Estabelecida Com Sucesso" );
            taStatus.setText("Conexão Não Estabelecids" );
            JOPM JOptionPaneMod = new JOPM( 2, "teste_de_conexao_listarTabelasDoBanco() \n"
                + e.getMessage() + "\n", "Conexao_Com_Banco_De_Dados_Derby_Alone" ); } //} }.start();                 
    }
    
}
